import { Inter } from "@next/font/google";
import Head from "next/head";

import { MorkBox } from "@/components/MorkBox";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Mork It!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MorkBox />
      </main>
    </>
  );
}
